language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

dist: xenial

cache: pip

jobs:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=lint

install:
  - pip install -r requirements/ci.txt


before_script:
  - coverage erase || true

script:
  - tox

after_success:
  - |
    if [[ "$TOXENV" != "lint" && -z "$PYPI_DEPLOY" ]]; then
      coverage combine || true
      coverage report
      codecov
    fi

stages:
  - test
